### PR TITLE
Split translated FAQ answer text 

### PR DESCRIPTION
**Pull request by gsvr**
Mike:
We need to break the items out to individual ones wrapped in translatable, then build them together here.

``` javascipt
var prev = $("Prev");
var next = $("Next");
var send = $("Send to me by SMS");
var footer_text = [
    "1. " + prev,
    "2. " + next, 
    "0. " + send
].join("\n");
```

George:
Problems with using .length on translation objects

### CODE REVIEW

**Comment by gsvr** [comment]
- [x] Move to new PaginatedState
- [x] Pass only the answer to states_answers (not whole response)

**Comment by gsvr** [comment]
@imsickofmaps Please review.  Justin did good work on this, it just worked.  We should probably re-check once we receive po files for this after going live.

**Comment by gsvr** [comment]
@imsickofmaps I just incorporated Justin's review from go-ndoh private line into this repo.  You can just merge as far as I'm concerned.  Not sure if we want to keep this repo updated in the future.

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
